ur-247: create flag icon component and add it to data transfer block
progressive-identity/uropa-ui pull request #66
Opened 2022-10-13 14:50 UTC by Djoudi21

I added a flag component  and added it to the data transfer block...thanks to Jules haha

2022-10-13 15:22 UTC, Jabuf requested changes

2022-10-13 15:22 UTC, Jabuf commented on src/components/basic/FlagIcon.vue
> +      :alt="`Drapeau de la ${country}`"
You should just use `${country}` instead.

2022-10-13 15:22 UTC, Jabuf commented on src/components/basic/FlagIcon.vue
> +  country: {
Maybe you should precise in the variable name what expected like `countryName` or `countryIso`.

2022-10-13 15:22 UTC, Jabuf commented on src/utils/constants/countriesInfosConstant.js
> +export const COUNTRIES_INFOS = {
We should make sure that the names are the same between our two files.

2022-10-13 20:38 UTC, prevostjules commented on src/components/basic/FlagIcon.vue
> +      :alt="`Drapeau de la ${country}`"
Yes, or use the $t to handle the translation (but I am not sure it is really required for now)

2022-10-14 09:26 UTC, Jabuf approved these changes
I've also added it to the DataCarrier block (which also had a chip with the country).
Otherwise this looks perfectly what we wanted, good job !

2022-10-14 09:26 UTC, merged